FROM dhspence/docker-hic

# File Author / Maintainer
MAINTAINER David Spencer

WORKDIR /opt/

RUN curl -L https://github.com/bwa-mem2/bwa-mem2/releases/download/v2.0pre2/bwa-mem2-2.0pre2_x64-linux.tar.bz2 | tar jxf -
